apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ngx-rollout-dep
  name: ngx-rollour-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ngx-rollout-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ngx-rollout-dep
    spec:
      volumes:
      - name: ngx-conf-vol
        configMap:
          name: ngx-conf-rollout
      containers:
      - image: nginx:1.21-alpine
        name: nginx
        resources: {}
        ports:
        - containerPort: 80

        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: ngx-conf-vol
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ngx-rollout-dep
  name: ngx-rollout-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ngx-rollout-dep
status:
  loadBalancer: {}
