apiVersion: v1
kind: Pod
metadata:
  name: nfs-pvc-pod

spec:
  volumes:
  - name: nfs-pvc-vol
    persistentVolumeClaim:
      claimName: nfs-static-pvc

  containers:
    - name: ngx-pvc-pod
      image: nginx:alpine
      ports:
      - containerPort: 80
      volumeMounts:
      - name: nfs-pvc-vol
        mountPath: /tmp

